### PR TITLE
💁 Fix list parsing.

### LINKED ISSUE #22: List conversion problem
Thanks for md2gemini - it's looking great!

Myself and a fellow member of the Void Linux docs team would like to make [the Void Handbook](https://docs.voidlinux.org/) available in geminispace, and md2gemini seems like it could it could significantly facilitate this. :-)

However, running [about/index.md](https://raw.githubusercontent.com/void-linux/void-docs/master/src/about/index.md) through md2gemini takes a source list that looks like:

    - The [XBPS](https://github.com/void-linux/xbps) package manager, which is
       extremely fast, developed in-house, and performs checks when installing
       updates to ensure that libraries are not changed to incompatible versions
       which can break dependencies.
    - The [musl libc](https://musl.libc.org/), which focuses on standards compliance
       and correctness, has first class support. This allows us to build certain
       components for musl systems statically, which would not be practical on glibc
       systems.
    - The [LibreSSL](https://www.libressl.org/) fork is used instead of the mainline
       OpenSSL library. Developed as part of the OpenBSD project, LibreSSL is
       dedicated to the security, quality, and maintainability of this critical
       library.

and produces:

    * The XBPS[6] package manager, which is
    * extremely fast, developed in-house, and performs checks when installing
    * updates to ensure that libraries are not changed to incompatible versions
    * which can break dependencies.
    * The musl libc[7], which focuses on standards compliance
    * and correctness, has first class support. This allows us to build certain
    * components for musl systems statically, which would not be practical on glibc
    * systems.
    * The LibreSSL[8] fork is used instead of the mainline
    * OpenSSL library. Developed as part of the OpenBSD project, LibreSSL is
    * dedicated to the security, quality, and maintainability of this critical
    * library.

The Markdown used for the Handbook is [Versioned Markdown](https://github.com/bobertlo/vmd).

cc: @ericonr

### PR DESCRIPTION
**Pull request by ericonr**
Newlines inside list items should be accounted for, so the text returned
by GeminiRenderer.list_item() should be a single line. That way,
GeminiRenderer.list() can do the right thing with the list, without
having to worry about newlines that aren't item separators.

---

Fixes #22 

Hopefully I picked a good emoji c:

### CODE REVIEW

**Comment by makeworld-the-better-one** [comment]
Thanks for adding this! I hadn't found the time to work on it. Could you add some tests though? You can create a new file in the `tests` folder, called `test_lists.py`. You can refer to the other test files for an example of how the file should work/look. Please add (at least) the original Void Linux list (with the minimum amount of preceding text to cause the issue), so that this bug won't regress later.

> Hopefully I picked a good emoji c:

No worries :smile:\
The emojis are from [gitmoji](https://gitmoji.carloscuesta.me/) though btw.

**Comment by ericonr** [comment]
> The emojis are from gitmoji though btw.

How do I use them? Just make the commit message `:bug: Fix list parsing` ?

**Comment by makeworld-the-better-one** [comment]
@ericonr Don't worry about it. But if you're interested, you can copy the emoji manually to the beginning of your commit messages, or you can use [gitmoji-cli](https://github.com/carloscuesta/gitmoji-cli).

**Comment by ericonr** [comment]
And sure, will add tests. Can't do it right now, so I will ping you when I'm done.

**Comment by ericonr** [comment]
@makeworld-the-better-one apparently mistune + my renderer only really works with the VMD format we use for void-docs... See the tests I added, a lot of them break unless the second line of an item is indented with 3 spaces. And the parsing seems to change for some of the cases as well.

**Comment by ericonr** [comment]
I have managed to fix most tests, the only ones still broken are for cases like

```
- item
item (no indentation)
```

and

```
- item
 item (one space for indentation)
```

Those are either due to the markdown spec of issues in mistune, since they are being parsed as separate text, not part of the `list_item`.

**Comment by makeworld-the-better-one** [comment]
Thanks for adding tests!

I hope you don't mind, I've pushed a commit (e18a7ca) that reorganizes the tests so that's it's easy to test for any number of spaces.

I'm okay with the no-space and single-space cases not working, so I've removed them and all tests pass now.

After adding the Void example as a test I will feel good to merge. Feel free to do that, or I can later.

**Comment by ericonr** [comment]
Ok, you want the full block? Can do! And I don't mind, thanks for making them more concise.

**Comment by makeworld-the-better-one** [comment]
Actually it's fine sorry, I misunderstood. There is no need.

I will merge and make a new release in the next day or so. Thanks again!

**Comment by ericonr** [comment]
Oh ok, thanks a lot!

**Pull request merged**
