### PR TITLE
✨ Add API parameter rellink_func

### LINKED ISSUE #26: Transform local links with no extension to links with .gmi extension
Hello,

This library is very useful, thanks for all the work.

I am aware af the `md_links` parameter about transforming local links with the `.md` extension to the `.gmi` extension. However, some dynamic markdown-based CMS like PicoCMS hide the `.md` extension in URLs for aesthetic purpose, so local links in source mardown files do not contain the `.md` extention.

Wouldn't it be interresting to extend the local `.md`-to-`.gmi` link replacement to cover that use case?

Thanks.

EDIT: Maybe even better: an option to apply a custom function to any local links.

### PR DESCRIPTION
**Pull request by raspbeguy**
This functions enable to provide a custom function to treat local links.
Fix #26

### CODE REVIEW

**Comment by makeworld-the-better-one** [comment]
Thanks for the PR. I was thinking this function would accept any link though, as I find that more versatile. Maybe the user wants to convert what were previously absolute links on their homepage to relative ones for Gemini, or wants to change Wikipedia links to ones that link to a Gemini Wikipedia mirror, etc.

Could you modify the code to work for all URLs? And also document the parameter a bit more? Mention what input it should be able to take (a single string) and what the function should output. Thank you!

**Comment by raspbeguy** [comment]
Ok, working on it.

**Comment by makeworld-the-better-one** [comment]
Thanks for making the changes. I made a small commit to use `callable` before calling the func. The only thing I forgot to mention was tests. Could you add some test cases? See `tests/` for an example file layout. For example, you could write a demo link func that replaces every URL with `foo`, and make sure that different types of URLs are all replaced -- absolute, relative, etc.

Thanks!

**Comment by raspbeguy** [comment]
I don't know what's wrong.

**Comment by raspbeguy** [comment]
Here we go.

**Comment by makeworld-the-better-one** [comment]
Thanks! And yeah, you need to format with black to get tests to pass sorry. I'll merge this now. Let me know if you'd like a new release for this, otherwise I'll leave it for now.

**Pull request merged**
