### PR TITLE
fix: --write does not respect full filepath.

### PR DESCRIPTION
**Pull request by danielcft**
### --write truncates the filepath (ex: "~/src/a.md"-> "a.md).
This seems somehow unexpected. I would expect it to write to filepath that I passed as parameter.
Also this behavior differs from other tools such as pandoc that will honor the filepath.

Furthermore the -dir option seems redundant since one can already write to stdout (and use redirection to accomplish the same goal)

### Modifications:
- --write uses full paths
- Remove redundant --dir flag

### CODE REVIEW

**Comment by danielcft** [comment]
To illustrate the issue consider a typical use case of md2gemini  - a  script that invokes md2gemini on each file in a directory with nested directories.
```
#!/bin/bash
for filename in **/*.md
do
	md2gemini --write "${filename}" 
done
```
This will result in files being written to the current dir  (instead of writing them next to the .md counterpart)

**Comment by makeworld-the-better-one** [comment]
I think this makes more sense, thanks for your PR.

I'd prefer if you didn't make the breaking change of remove `--dir`, and I still think it's a useful flag. Could you change your PR so that `--dir` defaults to the directory of each Markdown file, but can still be manually set?

**Comment by makeworld-the-better-one** [comment]
@danielcft is this ready for review? Recent changes look good.

**Comment by danielcft** [comment]
@makeworld-the-better-one Yes it's ready for review, thanks for the suggestion.

**Comment by makeworld-the-better-one** [comment]
Sorry for taking so long to get back to you. Unfortunately tests are failing and so that will need to be fixed. Let me know if you need help understanding any of the issues, or if some of the failures don't make sense. I'll try and respond more promptly.

**Comment by danielcft** [comment]
Sorry I can't commit to fix those as I don't have time. So I am closing the PR.

**Pull request closed without merging**
