### PR TITLE
This fixes the problem of new lines being eaten in code blocks in lists

### PR DESCRIPTION
**Pull request by its-teal**

### CODE REVIEW

**Comment by makeworld-the-better-one** [comment]
Thanks for this fix! Another hack on the top of the pile :D

Unfortunately right now it's causing some other tests to fail, specifically some of the ones in `test_list.py`. You can run `pytest` to see what the issues are. Basically your change is breaking some spaces in other lists. It's possible those tests are kind of wrong, but the current output is definitely incorrect. Let me know if you think the tests should be changed in some way.

Thanks again!

**Comment by its-teal** [comment]
Oh, I didn't even see those.  I wasn't sure how you were running the tests, I ended up kludging together a script to call them.

I'll go take a look and submit an update later.

**Comment by its-teal** [comment]
What tool do you run for the formatting?  I didn't notice it until after I pushed, I'm hoping I didn't undo any of it...

**Comment by its-teal** [comment]
Also, pytest runs clean for me with this change.

**Comment by makeworld-the-better-one** [comment]
I'm using [black](https://github.com/psf/black) for formatting, and I run `black --exclude 'unitable\.py' md2gemini tests`.

**Pull request merged**
